language: python

python:
  - "3.6"

cache: pip

install:
  - sudo apt-get update
  - python3.6 -m pip install -r requirements.txt
  - python3.6 -m pip install docker-py

script:
  - python3.6 tests.py
