version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - postgres_db
      - redis_db
    links:
      - redis_db
    ports:
      - "5000:5000"
    env_file:
      - ".env.web"
    command: gunicorn app:server --preload --workers=6 --timeout 120 --graceful-timeout 120 --max-requests 5 --log-level=info -b :5000
  postgres_db:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - ".env.db"
  redis_db:
    image: "redis:latest"
    restart: always
    volumes:
      - ./redis-data:/data:z
    command: redis-server --bind redis_db --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy volatile-ttl --appendonly yes
volumes:
  postgres-data:
  redis-data:
