version: '3'
services:
  web:
    build:
      context: .
      dockerfile: "Dockerfile"
    network_mode: "host"
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    env_file:
      - ".env.web"
    command: gunicorn app:server --preload --workers=2 --threads=2 --timeout 180 --max-requests 5 --log-level=info
  db:
    image: "postgres:latest"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    env_file:
      - "/.env.db"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
volumes:
  postgres_data:
