name: Test & Build

on:
  push:
    branches:
      - master
      - development
    tags:
      - v*
  pull_request:
    branches:
      - master
  release:
    types:
      - published
      - created
      - edited

jobs:
  job_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python3.6 x64
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install docker-py
      - name: Run tests.py
        run: |
          python tests.py
  job_build:
    needs: job_tests
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
          registry: docker.pkg.github.com
          tags: |
            user/conplot:latest
            user/conplot:v0.2.4
          file: .docker/Dockerfile
          push: true
          repository: filomenosanchez/conplot/conplot

