name: Build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
  release:
    types:
      - published
      - created
      - edited

jobs:
  jobs_tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install docker-py
      - name: Run tests
        run: |
          python tests.py
